import conway
import matplotlib.pyplot as plt
import numpy as np

N = 64
life = conway.GameOfLife(N)

# 1, Lightweight Spaceship (LWSS)
lwss = """
.O..O
O....
O...O
OOOO.
"""
plt.figure(0)
life.insertFromPlainText(lwss, pad=2)
cells = life.getStates()
plt.gray()
plt.imshow(cells)
ax = plt.gca()
ax.set_xticks(np.arange(-.5, N, 1), minor=True)
ax.set_yticks(np.arange(-.5, N, 1), minor=True)
ax.grid(which='minor', color='w', linestyle='-', linewidth=1)
plt.title("Lightweight Spaceship (LWSS) Pattern")

# Reset grid for next pattern
life.grid = np.zeros((N, N), np.int64)

# 2: Lobster
lobster = """
............OOO.........
............O...........
.............O..........
................OO......
............OO..........
.............OO.........
............O.OO........
..............O.OO......
..............O...O.....
...............OOO.O....
....................O...
..OO.O.O............O...
O.O.OO..............O...
O....O.OO.............OO
......O...O......OO.OO.O.
..OO.....O.......O.OO...
..OO....O.O......OO.....
.........O.....O...O...O.
..........O.OO....OO....
...........OO...O....O.O
...............O.......OO
...............O....O...
..............O...O.....
..............O.....OO..
...............O.....O..
"""
plt.figure(1)
life.insertFromPlainText(lobster, pad=2)
cells = life.getStates()
plt.gray()
plt.imshow(cells)
ax = plt.gca()
ax.set_xticks(np.arange(-.5, N, 1), minor=True)
ax.set_yticks(np.arange(-.5, N, 1), minor=True)
ax.grid(which='minor', color='w', linestyle='-', linewidth=1)
plt.title("Lobster Pattern")

# Reset grid
life.grid = np.zeros((N, N), np.int64)

# Pattern 3: Loafer Synthesis
loafer = """
.................................O
...............................OO
................................OO
.........O.......................
.O.......O.......................
..O.....OOO......................
OOO..............................
.................................
.................................
.....O...........................
......O..........................
....OOO..........................
........................O.O......
.........................OO......
.........................O.......
.................................
...........................O.O...
...........................OO....
............................O....
...............................OOO
...............................O.
................................O.
.................................
.................................
.................................
.................................
.................................
.....OO..........................
......OO.........................
.....O...........................
.................................
"""
plt.figure(2)
life.insertFromPlainText(loafer, pad=2)
cells = life.getStates()
plt.gray()
plt.imshow(cells)
ax = plt.gca()
ax.set_xticks(np.arange(-.5, N, 1), minor=True)
ax.set_yticks(np.arange(-.5, N, 1), minor=True)
ax.grid(which='minor', color='w', linestyle='-', linewidth=1)
plt.title("Loafer Synthesis Pattern")

plt.show()
